development: &default
  adapter: postgresql
  database: backbone_data_bootstrap_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: <%= ENV['FIGRAILS_DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['FIGRAILS_DB_1_PORT_5432_TCP_PORT'] %>

test:
  <<: *default
  database: backbone_data_bootstrap_test
